name: Push Docker image
on:
  push:
    tags:
      - v*
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_IMAGE_PLATFORM: linux/amd64,linux/arm64/v8
          REPOSITORY_NAME: ${{ github.REPOSITORY }}
        run: |
          IFS='/' read -ra repository_name_array <<<"$REPOSITORY_NAME"
          DOCKER_IMAGE_NAME=$(echo $DOCKER_HUB_USERNAME/${repository_name_array[1]} | tr '[:upper:]' '[:lower:]')
          DOCKER_IMAGE_VERSION=${GITHUB_REF#refs/*/}
          docker buildx build \
            --platform "$DOCKER_IMAGE_PLATFORM" \
            --output "type=image,push=true" \
            --tag "$DOCKER_IMAGE_NAME":"$DOCKER_IMAGE_VERSION" \
            --tag "$DOCKER_IMAGE_NAME":latest \
            --file ./Dockerfile .
